name: Static analysis
on:
  push:
    branches: [ main, stable/15, stable/14, stable/13 ]
  pull_request:
    branches: [ main, stable/15, stable/14, stable/13 ]
  pull_request_target:
    branches: [ main, stable/15, stable/14, stable/13 ]
    types: [ opened, synchronize, reopened ]
    paths:
      - '**.c'
      - '**.h'
      - '**.cc'
      - '**.cpp'
      - '**.cxx'
      - '**.hpp'

permissions:
  contents: read
  pull-requests: write
  issues: write
  security-events: write
  checks: write
  statuses: write

jobs:
  cppcheck:
    name: Cppcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}

      - name: Install cppcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y cppcheck

      - name: Run cppcheck
        run: |
          cppcheck sys/amd64 sys/arm sys/arm64 sys/riscv \
            -icontrib/ -icrypto/ -ietc/ -ignu/ -iinclude/ -ikerberos/ \
            -ikrb5/ -ilibexec/ -itools/ -itarget/ -itests/ -icddl/ \
            -istand/ -isecure/ -ishare/ -irescue/ -ibin/ -iusr.sbin/ \
            -ilib/ -ietc/ -isbin/ -isys/dev/ -iboot/ -iboot/common/ -iboot/i386/ \
            --enable=warning,performance,portability \
            --inconclusive \
            --platform=unix64 \
            --std=c11 \
            --suppress=missingIncludeSystem \
            --suppress=unknownMacro \
            --suppress=syntaxError \
            --check-level=exhaustive \
            --force \
            -j $(nproc) \
            --xml \
            --output-file=report.xml .

      - name: Convert cppcheck report to SARIF
        uses: Flast/cppcheck-sarif@v2
        with:
          input: report.xml
          output: report.sarif

      - name: Upload cppcheck SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: report.sarif
          category: cppcheck

  cpp-linter-review:
    name: cpp-lint-review
    runs-on: ubuntu-latest
    needs: cppcheck
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}

      - name: Run C/C++ Linter
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          thread-comments: ${{ (github.event_name == 'pull_request_target' && 'true' || 'false') || (github.event_name == 'pull_request' && 'true' || 'false')  }}
          file-annotations: true
          extensions: "c,h,cpp,hpp,cc,cxx"
          tidy-review: ${{ (github.event_name == 'pull_request_target' && 'true' || 'false') || (github.event_name == 'pull_request' && 'true' || 'false') }}
          style: ''
      - name: Fail fast if issues found
        if: steps.linter.outputs.checks-failed > 0
        run: |
          echo "Linter found errors! PoÄet: ${{ steps.linter.outputs.checks-failed }}"
          exit 1